fix(DiscordJS): fix the way that the client filler gets the shard ID in v12
dbots-pkg/dbots.js pull request #184
Opened 2021-03-27 07:44 UTC by EndBug

I noticed that the [v12 `ShardClientUtil`](https://discord.js.org/#/docs/main/v12/class/ShardClientUtil) does not contain the ID of the shard you're using. I figured out that the only way to get the shard id is to get a guild and take it from there. 

I'm not sure about this though: that strategy relies on the fact that every guild cached will have the same shard ID. Are we sure about that? Is it possible that selecting a random guild will result in the wrong shard ID? Is there a better alternative (like maybe taking the most used shard ID)?

Let me know what you think

2021-03-27 17:21 UTC, Snazzah commented
You can read off of `client.options.shards` (shard ID) and `client.options.shardCount`.

2021-03-28 12:03 UTC, EndBug commented
I've updated the getter, is it better now?

2021-03-28 17:43 UTC, Snazzah requested changes
After this, LGTM

2021-03-28 17:43 UTC, Snazzah commented on src/Interface/Clients/DiscordJS.ts
> +      }
This is unnecessary, sorry about the confusion on my part.
```suggestion
```

2021-03-28 19:57 UTC, merged